Create logs file and actively check if frontend is healthy

diff --git a/.github/workflows/deploy_dev.yml b/.github/workflows/deploy_dev.yml
--- a/.github/workflows/deploy_dev.yml
+++ b/.github/workflows/deploy_dev.yml
@@ -90,6 +90,16 @@ jobs:
               working-directory: ./e2e-tests
               run: npx playwright install --with-deps
 
+            - name: Verify if the frontend is healthy 
+              run: |
+                response=$(curl -ks https://localhost)
+                if [[ $? -ne 0 ]]; then
+                  echo "Frontend is not healthy. Curl error : $?"
+                  exit 1
+                else
+                  echo "Frontend is healthy"
+                fi
+
             - name: Verify if the API is healthy
               run: |
                 response=$(curl -ks https://localhost/api/v1/healthcheck)
